# Generated by Django 4.1.4 on 2023-03-25 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='username',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
    ]
