# Generated by Django 4.1.4 on 2023-03-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.CharField(default='asdf', max_length=100),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='last_refresh',
            field=models.CharField(max_length=100),
        ),
    ]
