# Generated by Django 4.1.4 on 2023-08-27 14:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_remove_userinfo_first_name_remove_userinfo_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('last_refresh', models.CharField(max_length=100)),
                ('email_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
        migrations.RemoveField(
            model_name='application',
            name='username',
        ),
        migrations.AddField(
            model_name='application',
            name='date',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
