# Generated by Django 4.1.4 on 2023-08-27 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_user_delete_userinfo_remove_application_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='date',
        ),
    ]
