# Generated by Django 4.1.4 on 2023-08-27 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_remove_application_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
