# Generated by Django 4.1.4 on 2023-08-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_rename_user_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='email',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='users',
            name='user_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
